### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by KerenChandran** [patnaa2/waterbud#1]
## BACKEND FOR CLIENT
- [x] Write connect_to_server script from client side
  - [x] Create network and what not from there
- [x] Work on api endpoints on flask
  - [x] Historical Data 
  - [x] Pad data with 0s
  - [x] Thresholds
  - [x] Websockets 
  - [x] Add new sensors
  - [x] Notifications
  - [x] Tips
- [x] Setup mongo/some db to store all this data in a clean way
- [x] Generate Tips async
- [x] Notifications async
- [x] Update historical data with live data
- [x] Generate monthly summaries
- [x] pricing 
- [ ] fix resolution of data in endpoints and sensor data
- [x] Remove 0s from getting added to db
- [x] setup all the data, dbs for production
  - [x] change db to waterbud in several scripts 
  - [x] backfill data appropraitely
  - [x] test all endpoints
  - [x] generate monthly summaries
- [x] figure out how to set date to edt in pi
- [ ] fix double counting for backfill data
## HISTORICAL DATA
- [ ] Trapezoidal representation of flow for timeseries data
- [x] Convert all (timestamp, flow) tuples into dictionaries
- [x] N-day historical data generation. (Upper bound is previous day).
## FRONTEND FOR CLIENT
- [x] HighCharts Integration
- [x] Historical Daily Usage View
- [x] Historical Hourly Usage View
- [x] Live Usage View
- [x] Websockets for Live Data
- [x] Setting Threshold Screen
- [x] User Profile Details
- [x] Home Screen Layout
- [x] Spinner
- [x] Styles for the website
### Sensor Screens
- [x] Add Sensor
- [x] Display all Sensors
  - [ ] Display via Table Format
  - [x] Display via Card Grid Format
- [x] Remove Sensors
- [x] Edit Sensors
### Tips
- [x] Info for Tips: Image, Description, Benefits
- [x] List tips for each room on the back of the card
  - [x] Include see more button at bottom which populates modal
### Notifications
- [x] Setup Async Notifications Call (currently when user exits live view)
- [x] Display dynamic counter based on length of new notifications
- [x] On click, execute POST to server to mark notifications as read
- [x] Show notifications in modal; Separated into two sections (new and recent)
### Testing before Demo
- [x] Sensor on Keren's personal network
- [x] A full walk through with all the moving components, especially all the backend stuff
- [x] Leak detection
